export const ACTIOS = {
  ActiveShowCart: "ActiveShowCart",
  dataCart: "dataCart",
  activeQuickView: "activeQuickView",
  dataWishList: "dataWishList",
  dataFilterBrand: "dataFilterBrand",
  dataFilterSize: "dataFilterSize",
  dataFilterColor: "dataFilterColor",
  dataFilterPriceUnder200: "dataFilterPriceUnder200",
  dataFilterPriceOver1000: "dataFilterPriceOver1000",
  dataFilterPrice200To500: "dataFilterPrice200To500",
  dataFilterStar: "dataFilterStar",
  dataFilter: "dataFilter",
  page_limit_ByProduct: "page_limit_ByProduct",
  paginationByFilterProduct: "paginationByFilterProduct",
  dataProductFilter: "dataProductFilter",
  dataAddress: "dataAddress",
  loading: "loading",
  loadingCart: "loadingCart",
  loadingDeleteCart: "loadingDeleteCart",
  loadingPageCart: "loadingPageCart",
  loadingQuickView: "loadingQuickView",
  totalStar: "totalStar",
  dataArrOrderClient: "dataArrOrderClient",
  loadingOrderClient: "loadingOrderClient",
  dataAddOrder: "dataAddOrder",
  //admin
  dataFilterStyle: "dataFilterStyle",
  dataAllProduct: "dataAllProduct",
  filterPagination: "filterPagination",
  filterPaginationAllUser: "filterPaginationAllUser",
  loadingAllProduct: "loadingAllProduct",
  dataAllProductDetail: "dataAllProductDetail",
  dataAllUser: "dataAllUser",
  dataAllTypeProduct: "dataAllTypeProduct",
  dataAllOrder: "dataAllOrder",
  filterPaginationAllOrder: "filterPaginationAllOrder",
  dataAllOrderDetail: "dataAllOrderDetail",
  dataAllCoupon: "dataAllCoupon",
  arrayMess: "arrayMess",
  arrayChat: "arrayChat",
  dataBoxChat: "dataBoxChat",

  //component
  activeNotify: "activeNotify",
  // dataProductSearch: "dataProductSearch",
  // dataProductDiscount: "dataProductDiscount",
};
