export const ACTIOS = {
  ActiveShowCart: "ActiveShowCart",
  dataCart: "dataCart",
  activeQuickView: "activeQuickView",
  dataWishList: "dataWishList",
  dataFilterBrand: "dataFilterBrand",
  dataFilterSize: "dataFilterSize",
  dataFilterColor: "dataFilterColor",
  dataFilterPriceUnder200: "dataFilterPriceUnder200",
  dataFilterPriceOver1000: "dataFilterPriceOver1000",
  dataFilterPriceFrom200To1000: "dataFilterPriceFrom200To1000",
  dataFilter: "dataFilter",
  dataProductFilter: "dataProductFilter",
  dataAddress: "dataAddress",
  loading: "loading",
  loadingCart: "loadingCart",
  loadingDeleteCart: "loadingDeleteCart",
  loadingPageCart: "loadingPageCart",
  loadingQuickView: "loadingQuickView",
  totalStar: "totalStar",
  dataArrOrderClient: "dataArrOrderClient",
  loadingOrderClient: "loadingOrderClient",
  //admin
  dataFilterStyle: "dataFilterStyle",
  dataAllProduct: "dataAllProduct",
  filterPagination: "filterPagination",
  filterPaginationAllUser: "filterPaginationAllUser",
  loadingAllProduct: "loadingAllProduct",
  dataAllProductDetail: "dataAllProductDetail",
  dataAllUser: "dataAllUser",
  dataAllTypeProduct: "dataAllTypeProduct",
  dataAllOrder: "dataAllOrder",
  filterPaginationAllOrder: "filterPaginationAllOrder",
  dataAllOrderDetail: "dataAllOrderDetail",
  dataAllCoupon: "",
  // dataProductSearch: "dataProductSearch",
  // dataProductDiscount: "dataProductDiscount",
};
